import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

import { dataProvider } from "@providers/data-provider";
import UiProvider from "@providers/ui-provider";
import { Refine, ResourceProps } from "@refinedev/core";
import routerProvider from "@refinedev/nextjs-router";
import "@styles/global.css";
import { IconChartBar, IconHome, IconShoppingCart } from "@tabler/icons-react";
import { Metadata } from "next";
import React, { Suspense } from "react";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

const resources: ResourceProps[] = [
  {
    name: "Main Dashboard",
    list: "/",
    meta: {
      icon: <IconHome />,
    },
  },
  {
    name: "NFT MarketPlace",
    list: "/",
    meta: {
      icon: <IconShoppingCart />,
    },
  },
  {
    name: "Data Tables",
    list: "/",
    meta: {
      icon: <IconChartBar />,
    },
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
       <head>
        <ColorSchemeScript />
      </head>
      <body>
        <Suspense>
          <UiProvider>
            {/* <DevtoolsProvider> */}
            <Refine
              resources={resources}
              routerProvider={routerProvider}
              dataProvider={dataProvider}
              options={{
                syncWithLocation: true,
                warnWhenUnsavedChanges: true,
                useNewQueryKeys: true,
                projectId: "sXyKYR-uoMAWV-NTZ337",
              }}
            >
              {children}
            </Refine>
          </UiProvider>
          {/* </DevtoolsProvider> */}
        </Suspense>
      </body>
    </html>
  );
}
