import AppProvider from "@providers/app-provider";
import { Metadata } from "next";
import React, { PropsWithChildren, Suspense } from "react";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

const DashboardLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <Suspense>
      <AppProvider>{children}</AppProvider>
    </Suspense>
  );
};
